const form=document.querySelector('#registration-form'),error=document.querySelector('#form-error'),success=document.querySelector('#success'),provinceSelect=form.elements.province,citySelect=form.elements.city,agenciesSection=document.querySelector('#agencies-section'),agencyMessage=document.querySelector('#agency-message'),agencyCount=document.querySelector('#agency-count'),agencySelect=document.querySelector('#agency-select'),agencySelectWrap=document.querySelector('#agency-select-wrap');
const cities={'آذربایجان شرقی':['تبریز','مراغه','مرند','میانه'],'آذربایجان غربی':['ارومیه','خوی','مهاباد','بوکان'],'اردبیل':['اردبیل','مشگین‌شهر','خلخال'],'اصفهان':['اصفهان','کاشان','نجف‌آباد'],'البرز':['کرج','فردیس','نظرآباد'],'ایلام':['ایلام','دهلران','مهران'],'بوشهر':['بوشهر','برازجان','گناوه'],'تهران':['تهران','ری','شهریار','اسلامشهر'],'چهارمحال و بختیاری':['شهرکرد','بروجن','لردگان'],'خراسان جنوبی':['بیرجند','قائن','طبس'],'خراسان رضوی':['مشهد','نیشابور','سبزوار'],'خراسان شمالی':['بجنورد','شیروان','اسفراین'],'خوزستان':['اهواز','دزفول','آبادان','خرمشهر'],'زنجان':['زنجان','ابهر','خرمدره'],'سمنان':['سمنان','شاهرود','دامغان'],'سیستان و بلوچستان':['زاهدان','چابهار','ایرانشهر'],'فارس':['شیراز','مرودشت','جهرم','کازرون'],'قزوین':['قزوین','تاکستان','آبیک'],'قم':['قم','سلفچگان'],'کردستان':['سنندج','سقز','مریوان'],'کرمان':['کرمان','سیرجان','رفسنجان','بم'],'کرمانشاه':['کرمانشاه','اسلام‌آباد غرب','سنقر'],'کهگیلویه و بویراحمد':['یاسوج','دهدشت','گچساران'],'گلستان':['گرگان','گنبدکاووس','علی‌آباد کتول'],'گیلان':['رشت','بندر انزلی','لاهیجان'],'لرستان':['خرم‌آباد','بروجرد','دورود'],'مازندران':['ساری','بابل','آمل','قائم‌شهر'],'مرکزی':['اراک','ساوه','خمین'],'هرمزگان':['بندرعباس','میناب','قشم','کیش'],'همدان':['همدان','ملایر','نهاوند'],'یزد':['یزد','میبد','اردکان']};
const digits=value=>String(value).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d));
function jalaliTimestamp(){document.querySelector('#jalali-timestamp').textContent=new Intl.DateTimeFormat('fa-IR-u-ca-persian',{dateStyle:'full',timeStyle:'short'}).format(new Date());}
function populateBirthDate(){const year=Number(digits(new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric'}).format(new Date())));for(let y=year;y>=1300;y--)form.elements.birthYear.add(new Option(y.toLocaleString('fa-IR'),y));for(let m=1;m<=12;m++)form.elements.birthMonth.add(new Option(m.toLocaleString('fa-IR'),m));for(let d=1;d<=31;d++)form.elements.birthDay.add(new Option(d.toLocaleString('fa-IR'),d));}
function clearAgencies(){agenciesSection.hidden=true;agencySelectWrap.hidden=true;agencySelect.required=false;agencySelect.innerHTML='<option value="">آموزشگاه را انتخاب کنید</option>';agencyCount.textContent='';}
async function loadAgencies(){const province=provinceSelect.value,city=citySelect.value;clearAgencies();if(!province||!city)return;agenciesSection.hidden=false;agencyMessage.textContent='در حال دریافت فهرست آموزشگاه‌ها…';try{const url=`/api/v1/agencies/?province=${encodeURIComponent(province)}&city=${encodeURIComponent(city)}`;const response=await fetch(url);const agencies=await response.json();if(!response.ok)throw new Error();if(!agencies.length){agencyMessage.textContent='آموزشگاهی برای این شهر در فهرست موجود نیست. می‌توانید ثبت‌نام را بدون انتخاب آموزشگاه ادامه دهید.';return;}agencyCount.textContent=`${agencies.length.toLocaleString('fa-IR')} آموزشگاه`;agencyMessage.textContent='آموزشگاه موردنظر خود را انتخاب کنید.';agencies.forEach(agency=>{const address=agency.address.length>110?`${agency.address.slice(0,110)}…`:agency.address;const detail=[agency.office_name,address].filter(Boolean).join(' — ');agencySelect.add(new Option(detail,agency.id));});agencySelectWrap.hidden=false;agencySelect.required=true;}catch{agencyMessage.textContent='دریافت فهرست آموزشگاه‌ها با خطا روبه‌رو شد. لطفاً دوباره تلاش کنید.';}}
provinceSelect.addEventListener('change',()=>{const list=cities[provinceSelect.value]||[];citySelect.innerHTML='<option value="">شهر را انتخاب کنید</option>';list.forEach(city=>citySelect.add(new Option(city,city)));citySelect.disabled=!list.length;clearAgencies();});citySelect.addEventListener('change',loadAgencies);
populateBirthDate();jalaliTimestamp();setInterval(jalaliTimestamp,30000);
function showError(message){error.textContent=message;error.hidden=false;}
form.addEventListener('submit',async event=>{event.preventDefault();error.hidden=true;if(!form.checkValidity()){showError('لطفاً همه فیلدهای الزامی را تکمیل کنید.');form.querySelector(':invalid').focus();return;}const data=new FormData(form);const payload={first_name:data.get('firstName'),last_name:data.get('lastName'),national_id:digits(data.get('nationalId')),birth_year:Number(data.get('birthYear')),birth_month:Number(data.get('birthMonth')),birth_day:Number(data.get('birthDay')),gender:data.get('gender')==='زن'?'woman':'man',grade:data.get('grade'),province:data.get('province'),city:data.get('city'),agency_id:data.get('agencyId')||null,parent_phone:digits(data.get('parentPhone')),email:data.get('email'),address:data.get('address'),consent:data.get('consent')==='on'};const button=form.querySelector('[type="submit"]');button.disabled=true;button.textContent='در حال ثبت درخواست…';try{const response=await fetch('/api/v1/registrations/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(Object.values(result).flat().join(' ')||'ثبت درخواست انجام نشد.');document.querySelector('#tracking-code').textContent=result.tracking_code;success.hidden=false;success.scrollIntoView({behavior:'smooth',block:'center'});form.reset();citySelect.disabled=true;citySelect.innerHTML='<option value="">ابتدا استان را انتخاب کنید</option>';clearAgencies();}catch(exception){showError(exception.message||'ارتباط با سرور برقرار نشد.');}finally{button.disabled=false;button.innerHTML='ثبت درخواست و دریافت کد پیگیری <span>←</span>';}});
