# Generated by Django 6.1.1 on 2026-09-18 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('birth_date_jalali', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('woman', 'زن'), ('man', 'مرد')], max_length=10)),
                ('grade', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('parent_phone', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('consent_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام دانش\u200cآموز',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای دانش\u200cآموزان',
                'ordering': ['-created_at'],
            },
        ),
    ]
