# Generated by Django 6.1.1 on 2026-09-18 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanoonAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=120)),
                ('office_name', models.CharField(max_length=160)),
                ('address', models.TextField(blank=True)),
                ('phone_numbers', models.CharField(blank=True, max_length=300)),
                ('source_url', models.URLField()),
                ('retrieved_at_utc', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'آموزشگاه قلم\u200cچی',
                'verbose_name_plural': 'آموزشگاه\u200cهای قلم\u200cچی',
                'ordering': ('province', 'city', 'office_name'),
                'constraints': [models.UniqueConstraint(fields=('province', 'office_name', 'source_url'), name='unique_kanoon_agency')],
            },
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='registrations.kanoonagency'),
        ),
    ]
